### ISSUE TITLE
No way to generate the handbook-data.json for non Significa workers

### ISSUE THREAD

**Issue by TheSonOfSocrates** [significa/significa.co#344]
Hello, I hope you are doing well.
I found a really amazing agency website from Github!
That is really awesome.
It was so impressed!!!
I strogly wanted to launch that product.
But I have got some error.

in page.server.ts, 
import handbook from '$root/handbook-data.json';

But I can't find handbook-data.json from project.
Please help me.
Thank you.
Best regards!

![image](https://github.com/significa/significa.co/assets/130851533/925335f0-8d36-4411-a771-90123baf820a)
![image](https://github.com/significa/significa.co/assets/130851533/8fcddc30-1aea-4951-9d13-c00dbcde7ce5)

**Comment by tofran** [comment]
Thank you for your kind words and interest in our project! We're thrilled to hear that you found our website interesting.

We apologize for the missing `handbook-data.json`, it is generated from our internal documentation system, and unfortunately, it contains sensitive information such as API keys that we cannot expose publicly.

However, we understand the importance of providing sample data for demonstration purposes. We shouldcreate a sanitized sample data that we can include in the repository for users like yourself to test without major issues.

Still one must understand that this repository follows an internal roadmap and this is not our top priorities. Consider this repo a way to see how we built our website and learn with it. Not really a template which can be used to build on top of, specially as in many cases it would violate the license.

Thank you once again for your interest and understanding.

**Comment by TheSonOfSocrates** [comment]
> Thank you for your kind words and interest in our project! We're thrilled to hear that you found our website interesting.
> 
> We apologize for the missing `handbook-data.json`, it is generated from our internal documentation system, and unfortunately, it contains sensitive information such as API keys that we cannot expose publicly.
> 
> However, we understand the importance of providing sample data for demonstration purposes. We shouldcreate a sanitized sample data that we can include in the repository for users like yourself to test without major issues.
> 
> Still one must understand that this repository follows an internal roadmap and this is not our top priorities. Consider this repo a way to see how we built our website and learn with it. Not really a template which can be used to build on top of, specially as in many cases it would violate the license.
> 
> Thank you once again for your interest and understanding.

Hi, Francisco
Thank you for your kind reply.
Actually, I strongly want to be a member your fantastic family.
I was so impressed.
I took a look at the open position. But I couldn't find any position open.
Is there any possibility for hiring full stack engineer?
Let me attach my resume here.
https://drive.google.com/file/d/1vNP1ZhV0H3InnbmqTUVCUMMHHpYJXNOf/view

Thank you.
Best regards.
Theofilos

**Comment by tofran** [comment]
Thank you very much! Yes we do not have an open position as of right now. We might open one soon, but unfortunately not open for full remote candidates.

Regardless, you application is in dafe hands, thank you for your interest. Expect to receive an email when we go thru the pending applicants.

**Comment by TheSonOfSocrates** [comment]
> Thank you very much! Yes we do not have an open position as of right now. We might open one soon, but unfortunately not open for full remote candidates.
> 
> Regardless, you application is in dafe hands, thank you for your interest. Expect to receive an email when we go thru the pending applicants.

Thank you very much.
I hope to look hear from you soon.

Best regards.
Theofilos
