### ISSUE TITLE
Showcase mobile

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa.co#57]
- [x] ~~Horizontal scroll~~
- [ ] Set up a `main` tag, then the reader view mode (in safari) can work
https://www.client9.com/designing-html-for-safari-reader-mode/
- [ ] Menu bottom in iPhone X (~ such a great product design, huh Apple!? ~);
![Screenshot 2019-05-16 at 11 51 09](https://user-images.githubusercontent.com/4838076/57848517-02c75980-77d1-11e9-8de9-5e327c87498c.png)
- [ ] Can't see the last items (~ so cool this new iPhone ~)
![Screenshot 2019-05-16 at 11 53 16](https://user-images.githubusercontent.com/4838076/57848634-4621c800-77d1-11e9-87af-b2e2dcd4ece0.png)

**Comment by pbrandone** [comment]
@danilowoz can I assign you?

**Comment by danilowoz** [comment]
I already tried to solve this issue, but unfortunately, I wasn't successful. iPhone X has a strange behavior on the scroll and I was not able to find a definitive solution. 

How much does it bother you? As it only happens on iPhone X or greater, for me it is not a big deal.
