### ISSUE TITLE
Menu mobile

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa.co#58]
- [ ] Weird behavior when the menu is opened and scroll down
![Screenshot 2019-05-16 at 11 42 42](https://user-images.githubusercontent.com/4838076/57848004-bfb8b680-77cf-11e9-8ad0-81a9c325a53b.png)

**Comment by pbrandone** [comment]
we should:
a) disable scroll and page interactions when menu is open (careful with mobile safari bottom bar appearing and elastic scrolling - needs to be thoroughly tested)
b) close the menu when interacting with anything else on the page.

**Comment by pbrandone** [comment]
@danilowoz wanna take care of this?

**Comment by andrefurt** [comment]
http://drops.significa.co/Screen-Shot-2019-05-21-16-27-10.54-1558452433
