### ISSUE TITLE
Header mobile coherence

### ISSUE THREAD

**Issue by danilowoz** [Significa/significa.co#86]
On all pages on small screens, the title is aligned to the left, except "About" and "Labs" pages the title is centered. My opinion is that the title aligned to the left is better to read on the mobile.

What do you think? 

<img src="https://user-images.githubusercontent.com/4838076/57921861-4cc64300-7896-11e9-9b98-6852b974ca7b.png" alt=" "  style="width: 50%" />

<img src="https://user-images.githubusercontent.com/4838076/57921863-4cc64300-7896-11e9-992a-61569c00b179.png" alt=" "  style="width: 50%" />

**Comment by pedroet** [comment]
@danilowoz we can allign it to the left on mobile
